apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scaled-to-zero-service
  namespace: knative-map-test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "0"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "scaled-to-zero"
