apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            name: nginx-ingress
            podTemplate:
              spec:
                nodeSelector:
                  app: nginx
