apiVersion: acme.cert-manager.io/v1
kind: Order
metadata:
  name: example-com-order
  namespace: default
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1d6Q0NBVU1DQVFBd0ZqRVVNQklHQTFVRUF3d0xaWGhoYlhCc1pTNWpiMjB3Z2dFaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNNNGhCZStncmtnSG5oemVOZm5HdWVTWkRXQ2dUMzRCc2RyRSt0Cm05THd5TGx0QXNURVNHR2hROFdJaHJ6NEhJeFkzN0JmVitVejRVSUZraDlIdHRaR3RzdndJOEozWXlTTmZzMVgKSmdwRDFjQjRxSy9jVklrT3F6ZnlLOHFnRWxZKzhOT0N3bEtINkd1cktLQ0dkREdnUXYyM28yNHNCeEZWNFN5ZQpibjI0bktIbW1OT21Pd2x0dXpVOGhjbDV6OFVpYWErbU5JeENLSE1WSUIvRDBRazEvTTdjdUxOeTEvOWx0ZmR0CjRBWUJXVHM3WVBWL0Zia0EyVXliLzVNL29RMHROZnJmc04veXFsVFdxQ2VRd0xNV2kxRFliYmh6SjZnS2dGL2UKUGhQOEdha0RZeU9NZ1J4QlpEak85Y09SeEsrWTVlTnIwRnkwRlk1bXM4Qyt0TWlIQWdNQkFBR2dBREFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQUhmRzBsbmIvZGdaZHhGTDFQVXR1SFc5UGtSNzBIQ0IySXVhWTRML3lMNS9WCnZKc3NVUklJZUhiN3ZTeVVvRSszL2FMU1UvNUNtNkx2am43NXUrU0UyNXg4dEJhZnozOFNxVWFSaDhLNHFXMkEKZmluOHkvajZKSzJoMVJVTTBvK2M2NDB2MnNhOG4ycnZvOHpXb05UbFdoOFkrUDVjSFRpc3IwcTNnWFNINEg0YQpyNVNUdFVETFl2UjdoaFVBa3VKK2htNFR4NG5UQlphQzNETWpWeGFpd3JvSzlDdFNFOWR5YVlBaTJyZ3N4eFFHCkJWWTcrdUt5VWJaL3RsdHVJdFY0eGRveUhzcnNBSE9EaDNlR1kzNEhiLzlsQkd2b0lRNHJzQTE4Z0wzTG1QakwKZDZVbjQ1WHUxK2tjb1A5UEQwT3I1SUdyMTE1em5pcHg1R2ZBbE9jY2JBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
status:
  state: ready
  url: https://acme-v02.api.letsencrypt.org/acme/order/12345678
  authorizations:
    - https://acme-v02.api.letsencrypt.org/acme/authz/12345678
  finalizeURL: https://acme-v02.api.letsencrypt.org/acme/finalize/12345678/12345678
