/*
 * Copyright 2025 The Kubernetes Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Pure helpers for validating, parsing, and sanitising model-generated tool
 * arguments.
 */

// ---------------------------------------------------------------------------
// Schema completeness check
// ---------------------------------------------------------------------------

/**
 * Returns `true` when every required field in `inputSchema` is present and
 * free of placeholder strings, and no optional field contains a placeholder.
 *
 * Returning `true` lets callers skip an extra model round-trip to enhance the
 * arguments.
 *
 * @param args - Current argument values to validate for completeness.
 * @param inputSchema - Required fields and primitive field types from the tool schema.
 * @returns Whether required values exist and no supplied values are placeholders.
 */
export function checkIfArgumentsComplete(
  args: Record<string, unknown>,
  inputSchema: {
    /** Argument names required by the tool. */
    required?: string[];
    /** Primitive schema metadata keyed by argument name. */
    properties?: Record<
      string,
      {
        /** Expected primitive type used for numeric-string validation. */
        type?: string;
      }
    >;
  }
): boolean {
  const required: string[] = inputSchema.required ?? [];
  const properties = inputSchema.properties ?? {};

  const PLACEHOLDER_STRINGS = ['<optional', 'optional:', 'tbd', 'not specified'];
  /**
   * Checks whether a string contains a known placeholder marker.
   *
   * @param v - Argument string to inspect.
   * @returns Whether the string contains a placeholder marker.
   */
  const isPlaceholder = (v: string) => PLACEHOLDER_STRINGS.some(p => v.toLowerCase().includes(p));

  for (const field of required) {
    const value = args[field];
    if (value === undefined || value === null || value === '') return false;
    if (typeof value === 'string' && isPlaceholder(value)) return false;
  }

  for (const [key, value] of Object.entries(args)) {
    if (typeof value === 'string' && isPlaceholder(value)) return false;
    const fieldSchema = properties[key];
    if (fieldSchema?.type === 'number' && typeof value === 'string') {
      if (!/^-?\d+(\.\d+)?$/.test(value)) return false;
    }
  }

  return true;
}

// ---------------------------------------------------------------------------
// JSON response parsing
// ---------------------------------------------------------------------------

/**
 * Extracts a JSON object from a model text response and sanitises the result.
 *
 * Falls back to `{}` when no valid JSON object can be parsed.
 *
 * @param response - Model response containing JSON directly or within surrounding text.
 * @returns Sanitized parsed arguments, or an empty object when parsing fails.
 */
export function parseArgumentsFromResponse(response: string): Record<string, unknown> {
  try {
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    const parsed = jsonMatch ? JSON.parse(jsonMatch[0]) : JSON.parse(response.trim());
    return sanitizeLLMArguments(parsed);
  } catch {
    return {};
  }
}

// ---------------------------------------------------------------------------
// Argument sanitisation
// ---------------------------------------------------------------------------

/** Field name fragments whose values must be non-negative numbers. */
const NON_NEGATIVE_FIELDS = ['pet', 'adult', 'child', 'infant'];
/** Field name fragments whose string values should be coerced to numbers. */
const NUMERIC_FIELDS = ['price', 'adult', 'child', 'infant', 'pet', 'guest', 'count', 'min', 'max'];

/**
 * Cleans an object of tool arguments generated by a model:
 *
 * - Drops `null`/`undefined` values.
 * - Drops placeholder strings (`<optional …>`, `tbd`, `n/a`, …).
 * - Coerces numeric strings to `number` for well-known numeric field names.
 * - Drops negative values for person/pet count fields.
 * - Recursively sanitises nested plain objects.
 *
 * @param args - Model-generated argument object to sanitize recursively.
 * @returns A new object containing valid and normalized argument values.
 */
export function sanitizeLLMArguments(args: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(args)) {
    if (value === null || value === undefined) continue;

    if (typeof value === 'string') {
      const lower = value.toLowerCase();
      if (
        value.includes('<optional') ||
        value.includes('optional:') ||
        lower === 'tbd' ||
        lower === 'not specified' ||
        lower === 'n/a' ||
        value.trim() === ''
      ) {
        continue; // drop placeholder
      }

      // Coerce numeric-looking strings for numeric field names
      const keyLower = key.toLowerCase();
      if (/^-?\d+(\.\d+)?$/.test(value) && NUMERIC_FIELDS.some(f => keyLower.includes(f))) {
        result[key] = parseFloat(value);
        continue;
      }
    }

    if (typeof value === 'number') {
      const keyLower = key.toLowerCase();
      if (value < 0 && NON_NEGATIVE_FIELDS.some(f => keyLower.includes(f))) {
        continue; // drop invalid negative count
      }
    }

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      result[key] = sanitizeLLMArguments(value as Record<string, unknown>);
      continue;
    }

    result[key] = value;
  }

  return result;
}

// ---------------------------------------------------------------------------
// Field diff
// ---------------------------------------------------------------------------

/**
 * Returns the names of fields in `enhanced` that differ from (or are absent
 * in) `original` — i.e. the fields the model filled in or changed.
 *
 * @param original - Arguments before model enhancement.
 * @param enhanced - Arguments after model enhancement.
 * @returns Changed or newly populated field names, excluding `_llmEnhanced`.
 */
export function identifyEnhancedFields(
  original: Record<string, unknown>,
  enhanced: Record<string, unknown>
): string[] {
  return Object.entries(enhanced)
    .filter(([key, val]) => {
      if (key === '_llmEnhanced') return false;
      const orig = original[key];
      return (
        !(key in original) ||
        orig === null ||
        orig === undefined ||
        orig === '' ||
        JSON.stringify(orig) !== JSON.stringify(val)
      );
    })
    .map(([key]) => key);
}
