apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
  namespace: default
  labels:
    app: message-consumer
spec:
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        app: message-consumer
    spec:
      containers:
        - name: message-consumer
          image: some-registry/keda-message-consumer:latest
          imagePullPolicy: Always
          command:
            - consume
          env:
            - name: RABBITMQ_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: queue-connection-secrets
                  key: RABBITMQ_CONNECTION_STRING
            - name: REDIS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: queue-connection-secrets
                  key: REDIS_CONNECTION_STRING
          args:
            - '$(RABBITMQ_CONNECTION)'
            - '$(REDIS_CONNECTION)'
