import { KubeObject, KubeObjectInterface } from '@kinvolk/headlamp-plugin/lib/k8s/cluster';
import CustomResourceDefinition from '@kinvolk/headlamp-plugin/lib/k8s/crd';
import { useMemo } from 'react';
import { InstanceApiInfo, instanceApiInfoFromCrdSpec, matchesGeneratedCrd } from './instanceApi';
import { kroApiGroup, ResourceGraphDefinition } from './resourceGraphDefinition';

export type { CrdSpecLike, InstanceApiInfo } from './instanceApi';
export { instanceApiInfoFromCrdSpec, matchesGeneratedCrd } from './instanceApi';

/**
 * An instance of an RGD-generated API (a custom resource of the
 * generated CRD). The spec shape is defined by the RGD's SimpleSchema;
 * status carries kro's instance conditions and state plus any
 * CEL-projected fields the RGD declares.
 *
 * @see https://kro.run/docs/concepts/instances
 * @see https://github.com/kubernetes-sigs/kro/blob/main/api/v1alpha1/instance_state.go
 */
export interface KroInstance extends KubeObjectInterface {
  /** Instance spec as defined by the RGD's SimpleSchema. */
  spec?: Record<string, unknown>;
  status?: {
    /** kro's instance conditions (InstanceManaged, GraphResolved, ResourcesReady, Ready). */
    conditions?: {
      type: string;
      status: string;
      reason?: string;
      message?: string;
      lastTransitionTime?: string;
    }[];
    /** Instance lifecycle state, e.g. "ACTIVE", "IN_PROGRESS", "FAILED". */
    state?: string;
    /** CEL-projected status fields declared in the RGD schema. */
    [key: string]: unknown;
  };
}

/** A dynamically built KubeObject class for one generated API. */
export type InstanceClass = typeof KubeObject<KroInstance>;

/**
 * Classes are cached so the same generated API always maps to the same
 * class identity; recreating classes on each render would remount
 * DetailsGrid/useList consumers and break watches.
 */
const instanceClassCache = new Map<string, InstanceClass>();

/**
 * Build (or fetch from cache) a KubeObject class for a generated API.
 *
 * @param info - Group/version/plural/kind/scope of the API, typically
 *   taken from the generated CRD.
 * @returns A watchable class with stable identity per group/version/plural.
 */
export function makeInstanceClass(info: InstanceApiInfo): InstanceClass {
  const cacheKey = `${info.group}/${info.version}/${info.plural}`;
  const cached = instanceClassCache.get(cacheKey);
  if (cached) {
    return cached;
  }
  const instanceClass = class extends KubeObject<KroInstance> {
    static kind = info.kind;
    static apiName = info.plural;
    static apiVersion = `${info.group}/${info.version}`;
    static isNamespaced = info.isNamespaced;
  };
  instanceClassCache.set(cacheKey, instanceClass);
  return instanceClass;
}

/**
 * Discover the CRD generated by an RGD by matching group + kind from
 * spec.schema against the cluster's CRDs.
 *
 * @param rgd - The RGD whose generated CRD to find; null while loading.
 * @returns Live result: `crd` is null while loading or when the RGD is
 *   Inactive and never generated its CRD; `error` carries the CRD list
 *   error (e.g. RBAC denial) if any; `isLoading` is true until the CRD
 *   list resolves.
 */
export function useGeneratedCrd(rgd: ResourceGraphDefinition | null) {
  const [crds, error] = CustomResourceDefinition.useList();
  const generatedKind = rgd?.spec.schema?.kind;
  const generatedGroup = rgd?.spec.schema?.group || kroApiGroup;

  const crd = useMemo(() => {
    if (!crds || !generatedKind) {
      return null;
    }
    return (
      crds.find(candidate =>
        matchesGeneratedCrd(candidate.jsonData.spec, generatedGroup, generatedKind)
      ) ?? null
    );
  }, [crds, generatedKind, generatedGroup]);

  return { crd, error, isLoading: crds === null && !error };
}

/**
 * Build a live KubeObject class for the instances of an RGD's generated
 * API. The discovered CRD is the source of truth for the plural name,
 * scope, and storage version.
 *
 * @param rgd - The RGD whose instances should be watched; null while loading.
 * @returns `instanceClass`/`apiInfo` are null while the CRD is loading
 *   or missing; `error` and `isLoading` mirror {@link useGeneratedCrd}.
 */
export function useInstanceClass(rgd: ResourceGraphDefinition | null) {
  const { crd, error, isLoading } = useGeneratedCrd(rgd);

  const apiInfo = useMemo(() => instanceApiInfoFromCrdSpec(crd?.jsonData.spec), [crd]);
  const instanceClass = useMemo(() => (apiInfo ? makeInstanceClass(apiInfo) : null), [apiInfo]);

  return { instanceClass, apiInfo, error, isLoading };
}

/**
 * Label selector matching every resource kro created for an instance.
 * kro stamps its ownership labels on all resources it applies; there
 * are no ownerReferences (kro 0.9.x uses applysets).
 *
 * @param instance - The owning instance.
 * @returns Selector string for useList/watch calls.
 * @see https://github.com/kubernetes-sigs/kro/blob/main/pkg/metadata/labels.go
 */
export function instanceSubResourceSelector(instance: KubeObject<KroInstance>): string {
  return `kro.run/owned=true,kro.run/instance-id=${instance.metadata.uid}`;
}
