import { KubeObject, KubeObjectInterface } from '@kinvolk/headlamp-plugin/lib/k8s/cluster';
import CustomResourceDefinition from '@kinvolk/headlamp-plugin/lib/k8s/crd';
import { useMemo } from 'react';
import { kroApiGroup, ResourceGraphDefinition } from './resourceGraphDefinition';

/** An instance of an RGD-generated API (a custom resource of the generated CRD). */
export interface KroInstance extends KubeObjectInterface {
  spec?: Record<string, unknown>;
  status?: {
    conditions?: {
      type: string;
      status: string;
      reason?: string;
      message?: string;
      lastTransitionTime?: string;
    }[];
    state?: string;
    [key: string]: unknown;
  };
}

export interface InstanceApiInfo {
  group: string;
  version: string;
  plural: string;
  kind: string;
  isNamespaced: boolean;
}

export type InstanceClass = typeof KubeObject<KroInstance>;

/**
 * Classes are cached so the same generated API always maps to the same
 * class identity; recreating classes on each render would remount
 * DetailsGrid/useList consumers and break watches.
 */
const instanceClassCache = new Map<string, InstanceClass>();

export function makeInstanceClass(info: InstanceApiInfo): InstanceClass {
  const cacheKey = `${info.group}/${info.version}/${info.plural}`;
  const cached = instanceClassCache.get(cacheKey);
  if (cached) {
    return cached;
  }
  const instanceClass = class extends KubeObject<KroInstance> {
    static kind = info.kind;
    static apiName = info.plural;
    static apiVersion = `${info.group}/${info.version}`;
    static isNamespaced = info.isNamespaced;
  };
  instanceClassCache.set(cacheKey, instanceClass);
  return instanceClass;
}

/**
 * Discover the CRD generated by an RGD by matching group + kind from
 * spec.schema against the cluster's CRDs. The CRD is the source of
 * truth for the plural name and scope, which the RGD does not publish.
 * Returns a live result: crd is null while loading or when the RGD is
 * Inactive and never generated its CRD.
 */
export function useGeneratedCrd(rgd: ResourceGraphDefinition | null) {
  const [crds, error] = CustomResourceDefinition.useList();
  const generatedKind = rgd?.spec.schema?.kind;
  const generatedGroup = rgd?.spec.schema?.group || kroApiGroup;

  const crd = useMemo(() => {
    if (!crds || !generatedKind) {
      return null;
    }
    return (
      crds.find(
        candidate =>
          candidate.jsonData.spec?.group === generatedGroup &&
          candidate.jsonData.spec?.names?.kind === generatedKind
      ) ?? null
    );
  }, [crds, generatedKind, generatedGroup]);

  return { crd, error, isLoading: crds === null && !error };
}

/**
 * Build a live KubeObject class for the instances of an RGD's generated
 * API. Returns null while the CRD is loading or missing.
 */
export function useInstanceClass(rgd: ResourceGraphDefinition | null) {
  const { crd, error, isLoading } = useGeneratedCrd(rgd);

  const instanceClass = useMemo(() => {
    const spec = crd?.jsonData.spec;
    if (!spec?.group || !spec?.names?.plural || !spec?.names?.kind) {
      return null;
    }
    const storageVersion =
      spec.versions?.find((version: { storage?: boolean }) => version.storage)?.name ??
      spec.versions?.[0]?.name;
    if (!storageVersion) {
      return null;
    }
    return makeInstanceClass({
      group: spec.group,
      version: storageVersion,
      plural: spec.names.plural,
      kind: spec.names.kind,
      isNamespaced: spec.scope === 'Namespaced',
    });
  }, [crd]);

  return { instanceClass, error, isLoading };
}

/** Label selector matching every resource kro created for an instance. */
export function instanceSubResourceSelector(instance: KubeObject<KroInstance>): string {
  return `kro.run/owned=true,kro.run/instance-id=${instance.metadata.uid}`;
}
