apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: headlamp-demo-scram
  namespace: strimzi-headlamp-test
  labels:
    strimzi.io/cluster: strimzi-demo-zk
spec:
  authentication:
    type: scram-sha-512
