apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: headlamp-demo-tls
  namespace: strimzi-headlamp-test
  labels:
    strimzi.io/cluster: strimzi-demo-kraft
spec:
  authentication:
    type: tls
