apiVersion: kueue.x-k8s.io/v1beta2
kind: Cohort
metadata:
  name: default
spec:
  fairSharing:
    weight: "1"
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
      flavors:
        - name: default
          resources:
            - name: cpu
              nominalQuota: "12"
            - name: memory
              nominalQuota: 48Gi
        - name: spot
          resources:
            - name: cpu
              nominalQuota: "24"
            - name: memory
              nominalQuota: 96Gi
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: Cohort
metadata:
  name: engineering
spec:
  parentName: default
  fairSharing:
    weight: "0.75"
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
      flavors:
        - name: default
          resources:
            - name: cpu
              nominalQuota: "4"
              borrowingLimit: "8"
              lendingLimit: "2"
            - name: memory
              nominalQuota: 16Gi
              borrowingLimit: 32Gi
              lendingLimit: 8Gi
