/*
 * Copyright 2025 The Kubernetes Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ConversationMessage } from '@headlamp-k8s/ai-common/conversation/types';

export interface SessionExportOptions {
  messages: ConversationMessage[];
  cluster?: string;
  clusters?: string[];
  timestamp?: Date;
}

/**
 * Generates a structured Markdown report from an assistant conversation session.
 *
 * @param options - Session export configuration including messages and cluster metadata.
 * @returns Clean, formatted Markdown content suitable for issue attachments or incident logs.
 */
export function generateSessionMarkdown(options: SessionExportOptions): string {
  const { messages, cluster, clusters, timestamp = new Date() } = options;

  const clusterList = cluster ? [cluster] : clusters && clusters.length > 0 ? clusters : ['N/A'];

  const dateString = timestamp.toISOString().replace('T', ' ').substring(0, 19) + ' UTC';

  const lines: string[] = [
    '# Headlamp AI Assistant Session Report',
    '',
    `- **Date:** ${dateString}`,
    `- **Cluster(s):** ${clusterList.join(', ')}`,
    `- **Total Messages:** ${messages.length}`,
    '',
    '---',
    '',
    '## Conversation History',
    '',
  ];

  if (messages.length === 0) {
    lines.push('_No messages in this session._', '');
  } else {
    for (const msg of messages) {
      if (msg.isDisplayOnly && !msg.content) continue;

      const role = msg.role || 'unknown';
      let roleTitle = 'Message';
      if (role === 'user') {
        roleTitle = 'User';
      } else if (role === 'assistant') {
        roleTitle = 'AI Assistant';
      } else if (role === 'tool') {
        roleTitle = `Tool Result${msg.name ? ` (${msg.name})` : ''}`;
      } else if (role === 'system') {
        roleTitle = 'System';
      }

      lines.push(`### ${roleTitle}`);
      lines.push('');

      if (msg.content) {
        lines.push(msg.content.trim());
        lines.push('');
      }

      if (msg.error) {
        lines.push('> [!NOTE]');
        lines.push('> This message encountered an error during execution.');
        lines.push('');
      }

      lines.push('---', '');
    }
  }

  lines.push('*Report generated by Headlamp AI Assistant*');

  return lines.join('\n');
}
