apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-job-retry-failed
  namespace: volcano-lab
spec:
  schedulerName: volcano
  queue: volcano-lab-queue
  minAvailable: 1
  maxRetry: 2
  policies:
    - event: PodFailed
      action: RestartJob
  tasks:
    - name: worker
      replicas: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: busybox
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "echo fail && exit 1"]
