version: 0.4.0
name: headlamp_flux
displayName: Flux
createdAt: "2025-07-17T14:54:30Z"
logoURL: "https://raw.githubusercontent.com/headlamp-k8s/plugins/main/flux/logo.png"
description: A UI for viewing and managing Flux.
changes:
  - kind: changed
    description: "Improve overview with a filter and info for some Flux resources"
  - kind: added
    description: "Add check for null CR in certain components. Thanks to @andrew-ashvin ."
  - kind: added
    description: "Add flux 2.0.0 CRD versions. Thanks to @explsd ."
  - kind: fixed
    description: "Add types and fix unknown string function in Inventory"
  - kind: removed
    description: "Remove unneeded dependencies"
annotations:
  headlamp/plugin/archive-url: "https://github.com/headlamp-k8s/plugins/releases/download/flux-0.4.0/headlamp-k8s-flux-0.4.0.tar.gz"
  headlamp/plugin/archive-checksum: "SHA256:780dd7fcf5af9250dbff970e40c83b038722303418678bb752cc38bc84464930"
  headlamp/plugin/version-compat: ">=0.22"
  headlamp/plugin/distro-compat: in-cluster,web,docker-desktop,desktop
